# Generated by Django 2.0.6 on 2018-10-18 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Code', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=70)),
                ('Contact_No', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('CSI', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('College_Code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('Quiz', models.CharField(max_length=20)),
                ('Gaming', models.CharField(max_length=20)),
                ('Coding', models.CharField(max_length=20)),
                ('Webdesigning', models.CharField(max_length=20)),
                ('Androiddevelopment', models.CharField(max_length=20)),
                ('Groupdiscussion', models.CharField(max_length=20)),
            ],
        ),
    ]
